import { ActiveDesignsIcon, ActiveHomeIcon, ActiveMarketIcon, ActiveMessagesIcon, ActiveNetworkIcon, ActiveNotificationsIcon, ActiveSettingsIcon, DesignsIcon, HomeIcon, MarketIcon, MessagesIcon, NetworkIcon, NotificationsIcon, SettingsIcon } from "@/components/core/icons";

export const sideBarLinks = [
    {
        id:1,
        label:"Home",
        title:"home",
        icon:{
            normal:HomeIcon,
            active:ActiveHomeIcon
        },
        path:"/home"
    },
    {
        id:2,
        label:"Designs",
        title:"designs",
        icon:{
            normal:DesignsIcon,
            active:ActiveDesignsIcon
        },
        path:"/designs"
    },
    {
        id:3,
        label:"MarketPlace",
        title:"marketplace",
        icon:{
            normal:MarketIcon,
            active:ActiveMarketIcon
        },
        path:"/marketplace"
    },
    {
        id:4,
        label:"Network",
        title:"network",
        icon:{
            normal:NetworkIcon,
            active:ActiveNetworkIcon
        },
        path:"/network"
    },
    {
        id:5,
        label:"Messages",
        title:"messages",
        icon:{
            normal:MessagesIcon,
            active:ActiveMessagesIcon
        },
        path:"/messages"
    },
    {
        id:6,
        label:"Notifications",
        title:"notifications",
        icon:{
            normal:NotificationsIcon,
            active:ActiveNotificationsIcon
        },
        path:"#"
    },
    {
        id:7,
        label:"Settings",
        title:"settings",
        icon:{
            normal:SettingsIcon,
            active:ActiveSettingsIcon
        },
        path:"/settings"
    },    
]